# Generated by Django 4.2.7 on 2023-12-14 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_access', '0004_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_access.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_access.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_access.size')),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
