# Generated by Django 4.2.3 on 2023-12-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_customerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='identity.customer'),
        ),
    ]
