# Generated by Django 4.2.3 on 2023-12-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_remove_customerinfo_id_alter_customerinfo_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
