# Generated by Django 4.2.3 on 2023-12-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(default='processing', max_length=255)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('phone_num', models.CharField(default='', max_length=10)),
                ('address_1', models.CharField(default='', max_length=255)),
                ('address_2', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('province', models.CharField(default='', max_length=2)),
                ('postal_code', models.CharField(default='', max_length=7)),
                ('payment_method', models.CharField(default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='identity.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='inventories',
            field=models.ManyToManyField(through='ordering.OrderItem', to='catalog.inventory'),
        ),
    ]
