# Generated by Django 4.2.3 on 2023-12-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_access.color')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_access.product')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_access.size')),
            ],
        ),
    ]
