# Generated by Django 4.2.3 on 2023-12-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0002_color_size_remove_product_inventory_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='size_id',
            new_name='size',
        ),
    ]
