# Generated by Django 4.2.3 on 2023-12-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0003_rename_color_id_inventory_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
