# Generated by Django 4.2.3 on 2023-12-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0004_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
    ]
